Homework 1: Radko Vyacheslav
ok-technopolis-autumn-2022/Slava_Radko pull request #2
Opened 2022-09-28 20:44 UTC by radkoff26

HTML only markup with BEM methodology.

2022-09-29 06:15 UTC, fromanywhere requested changes
Неплохой заход.

Хороший фронтенд должен думать, зачем он делает задачу (что от него хотели получить, но недоговорили)

Эта домашка — про структуру документа и про возможности HTML.
Можно лучше.

2022-09-29 06:15 UTC, fromanywhere commented on index.html
> +            <img src="./assets/select.png" alt="select">
1) С точки зрения функционала выглядит, что тут должен быть другой элемент (какой?)
2) В любом случае, то, как именно выглядит этот элемент — это декоративное. Тег img используют, наоборот, не для оформления, а для контента (если пользователь загрузил картинку, это будет img; если нужно положить фон на элемент, это зона ответственности CSS)

-> Здесь точно лучше удалить картинку

2022-09-29 06:15 UTC, fromanywhere commented on index.html
> +                <i class="task__remove">&times;</i>
Какую семантическую роль играет тег i?

2022-09-29 06:15 UTC, fromanywhere commented on index.html
> +            <div class="todo-list__task task done">
если мы говорим про bem, то тут done не по методологии

2022-09-29 06:15 UTC, fromanywhere commented on index.html
> +                <a href="#" class="todo-footer__nav-link">All</a>
Какую семантическую роль играет ссылка? Насколько ссылка хороша для функционала вида «переключатель»? Как здесь можно сделать лучше?

2022-09-29 06:15 UTC, fromanywhere commented on index.html
> +            <a href="#" class="todo-footer__clear">Clear completed</a>
Здесь тоже лучше использовать другой тег (какой? почему?)

2022-09-29 06:15 UTC, fromanywhere commented on index.html
> +        <div class="todo-list">
Здесь имеет смысл подумать, можно ли использовать другой тег (зачем?)

2022-09-29 07:20 UTC, radkoff26 commented on index.html
> +                <i class="task__remove">&times;</i>
Да, я тут явно что-то накрутил - тут просто button должен бытью.

2022-09-29 07:23 UTC, radkoff26 commented on index.html
> +        <div class="todo-list">
Если вы имеете в виду тэг div в данном случае, то, в целом, по семантике его можно заменить на main, т.к. дальше идёт основной контент страницы.

2022-09-29 07:26 UTC, radkoff26 commented on index.html
> +            <div class="todo-list__task task done">
Согласен, поправлю.

2022-09-29 07:29 UTC, radkoff26 commented on index.html
> +                <i class="task__remove">&times;</i>
> Какую семантическую роль играет тег i?

Ну вообще тег i просто переводит текст в italic стиль, ну и вообще он нужен для какой-то дополнительной текстовой стилизации. Например, стилизация отдельной части текста внутри текста.

2022-09-29 07:31 UTC, radkoff26 commented on index.html
> +                <i class="task__remove">&times;</i>
Тег button же, в свою очередь, сможет правильно реализовать функционал для удаления текущей задачи из списка.

2022-09-29 07:34 UTC, radkoff26 commented on index.html
> +            <img src="./assets/select.png" alt="select">
То есть правильнее будет сделать пустой button со стилизованным картинкой background'ом?
Если так, то я, в целом, согласен, потому что так можно просто поставить дефолтную статическую картинку на background (сделать contain) и указывать размеры кнопки так, как потребуется.

2022-09-29 07:36 UTC, radkoff26 commented on index.html
> +            <img src="./assets/select.png" alt="select">
Хотя, с другой стороны, я не сказал бы, что, например, обернуть img или svg в button - это плохо (так ведь тоже делают).

2022-09-29 07:38 UTC, radkoff26 commented on index.html
> +                <a href="#" class="todo-footer__nav-link">All</a>
Ну, ссылка делает переход на другую страницу, очевидно, здесь я почему-то не подумал про функционал, а потому получилось не очень правильно. Ссылка не сможет нормально переключать списки.
В этом случае нужно использовать что-то вроде input[type="radio"], мне кажется.

2022-09-29 07:44 UTC, radkoff26 commented on index.html
> +            <a href="#" class="todo-footer__clear">Clear completed</a>
Я думаю, что здесь было бы целесообразнее использовать тег button, потому что по семантике это будет правильнее, а по функционалу в любом случае нужен будет eventListener, который будет очищать текущий список через JS.

2022-09-29 07:47 UTC, fromanywhere commented on index.html
> +            <img src="./assets/select.png" alt="select">
img — плохо, svg — нормально. Но сам button должен быть

2022-09-29 07:48 UTC, fromanywhere commented on index.html
> +                <i class="task__remove">&times;</i>
👍

2022-09-29 07:48 UTC, fromanywhere commented on index.html
> +                <a href="#" class="todo-footer__nav-link">All</a>
👍

2022-09-29 07:48 UTC, fromanywhere commented on index.html
> +            <a href="#" class="todo-footer__clear">Clear completed</a>
👍

2022-09-29 07:49 UTC, fromanywhere commented on index.html
> +        <div class="todo-list">
Нет

это список. Здесь возникает вопрос навигации и a11y. Оно может быть решено двумя разными путями — тегами или aria-атрибутами, но тегами правильнее

2022-09-29 07:53 UTC, radkoff26 commented on index.html
> +            <img src="./assets/select.png" alt="select">
Понял, спасибо!

2022-09-29 07:54 UTC, radkoff26 commented on index.html
> +        <div class="todo-list">
Точно, полностью согласен.

2022-09-29 07:58 UTC, radkoff26 commented
Спасибо за замечания! Вроде всё поправил.
Просто осталось много вредных привычек после React, по типу того, что разница очень мала между тегами, ибо много что зависит от state. С этого момента буду повнимательнее.

2022-09-29 08:06 UTC, fromanywhere requested changes

2022-09-29 08:06 UTC, fromanywhere commented on index.html
> +                    <input id="all" class="todo-footer__nav-switch" type="radio">
<img width="227" alt="image" src="https://user-images.githubusercontent.com/1042969/192974301-8a6144a3-3d4b-44eb-865d-1cb1c8106164.png">
Так быть не должно

2022-09-29 08:06 UTC, fromanywhere commented on index.html
> +                    <input id="active" class="todo-footer__nav-switch" type="radio">
Если контрол завернут в лейбл, for уже не нужен.

2022-09-29 08:06 UTC, fromanywhere commented on index.html
> +            <button class="add-form__add"></button>
Здесь стало лучше, но с точки зрения доступности всё еще нехорошо. Вам расскажут об этом в обозримом будущем, а PR пусть пока повисит открытым

2022-09-29 08:20 UTC, radkoff26 commented on index.html
> +                    <input id="all" class="todo-footer__nav-switch" type="radio">
Виноват, забыл name указать

2022-09-29 08:21 UTC, radkoff26 commented on index.html
> +            <button class="add-form__add"></button>
Вы про aria- атрибуты?

2022-09-29 08:24 UTC, radkoff26 commented
Всё исправил

2022-09-29 11:12 UTC, fromanywhere commented on index.html
> +            <button class="add-form__add"></button>
Важно, чтобы пользователь всегда мог понять, что делает тот или иной контрол.
Пример: сайт минцифры https://digital.gov.ru/ru/events/42023/
Пользователь должен понимать, что произойдет, до того как он нажмет на «глаз» в шапке 
<img width="152" alt="image" src="https://user-images.githubusercontent.com/1042969/193016714-4ceed5a3-8c31-48fe-95ea-c92124f7c963.png">
Сейчас у Вас примерно та же ошибка.
Есть несколько разных путей решения. Будет правильнее, если Вы узнаете о них от лектора, чем от меня (если лектор забудет сказать, имеет смысл задавать вопросы)

2022-09-29 11:25 UTC, radkoff26 commented on index.html
> +            <button class="add-form__add"></button>
Понял, спасибо! А дз я сдал по итогу?

2022-09-29 11:30 UTC, radkoff26 commented on index.html
> +            <button class="add-form__add"></button>
> Пользователь должен понимать, что произойдет, до того как он нажмет на «глаз» в шапке
То есть там это сделано неправильно?
Просто можно попробовать поставить атрибут title для того, чтобы пользователь при ховере на элемент мог увидеть, что он делает

2022-09-29 11:44 UTC, fromanywhere commented on index.html
> +            <button class="add-form__add"></button>
ДЗ сдается по принципу проаппрувленного PR. Нет аппрува — ДЗ не зачтено.
Другое дело, что в этом курсе нет фиксированных сроков сдачи.
Я ожидаю, что на сл. лекции будет продолжение рассказа про разметку, на основе которой в эту работу будут сделаны доработки

Что касается title — да, я бы в этом случае сделал бы именно так. Но нужно понимать, как это работает внутри — выяснить про accessibility tree, что его формирует и как это отлаживать

2022-09-29 11:53 UTC, radkoff26 commented on index.html
> +            <button class="add-form__add"></button>
Понял, хорошо, спасибо за ревью!

2022-10-08 12:07 UTC, radkoff26 commented
Поправил Accessibility страницы

2022-10-10 08:41 UTC, fromanywhere approved these changes

2022-10-10 08:41 UTC, fromanywhere commented on index.html
> +        <nav class="todo-footer__nav">
благодаря nav я не заставил Вас писать тут role

2022-10-10 08:49 UTC, merged