Homework 4: Radko Vyacheslav
ok-technopolis-autumn-2022/Slava_Radko pull request #5
Opened 2022-11-30 18:08 UTC by radkoff26

Homework 4 is done!
I also made a popup which allows user to change text of the task.

2022-12-02 11:31 UTC, fromanywhere requested changes
Много хорошего, нужно довести до ума

2022-12-02 11:31 UTC, fromanywhere commented on src/js/components/Todo.js
> +    button.addEventListener('click', callbackOnRemove)
Не хочется иметь listener на каждый элемент. Давайте сделаем делегирование

2022-12-02 11:31 UTC, fromanywhere commented on src/js/generator.js
> +let id = 1
это хорошо

2022-12-02 11:31 UTC, fromanywhere commented on src/js/index.js
> +    const checkboxes = todoList.querySelectorAll('.task__checkbox')
Тут статус тудушек инвертируется, а должен быть общий чек/ анчек

2022-12-02 11:31 UTC, fromanywhere commented on src/js/index.js
> +            for (let i = 0; i < todoList.children.length; i++) {
но можно же просто querySelector по `[data-index=${id}]`

2022-12-02 11:31 UTC, fromanywhere commented on src/js/index.js
> +                if (todos[i].id === id) {
здесь тоже непонятно, зачем цикл

2022-12-02 11:31 UTC, fromanywhere commented on src/js/index.js
> +    for (const item of children) {
убираем цикл

2022-12-02 14:03 UTC, radkoff26 commented on src/js/index.js
> +    const checkboxes = todoList.querySelectorAll('.task__checkbox')
а в задании было написано, что можно сделать и инвертирование статуса туду

2022-12-02 14:03 UTC, radkoff26 commented on src/js/index.js
> +    const checkboxes = todoList.querySelectorAll('.task__checkbox')
но не проблема, сделаю общий

2022-12-02 15:42 UTC, radkoff26 commented on src/js/index.js
> +            for (let i = 0; i < todoList.children.length; i++) {
точно

2022-12-02 17:18 UTC, radkoff26 commented
Пофиксил вроде всё. Надеюсь, я правильно понял первый комм
ентарий.

2022-12-05 09:53 UTC, fromanywhere requested changes

2022-12-05 09:53 UTC, fromanywhere commented on src/js/components/Todo.js
> +    const addListeners = () => {
Всё еще нет делегирования

2022-12-05 10:41 UTC, radkoff26 commented on src/js/components/Todo.js
> +    const addListeners = () => {
а что вы подразумеваете под делегированием?

2022-12-05 10:43 UTC, radkoff26 commented on src/js/components/Todo.js
> +    const addListeners = () => {
просто я не совсем понимаю, как можно обойтись без listener'ов через делегирование

2022-12-05 10:45 UTC, radkoff26 commented on src/js/components/Todo.js
> +    const addListeners = () => {
кажется понял

2022-12-05 10:45 UTC, radkoff26 commented on src/js/components/Todo.js
> +    const addListeners = () => {
вы про делегирование событий говорили видимо

2022-12-05 10:46 UTC, fromanywhere commented on src/js/components/Todo.js
> +    const addListeners = () => {
Ну, вешается единый обработчик куда-нибудь наверх — например, на body. События всплывают, обработчик понимает, откуда они прилетели по e.target и, возможно, промежуточным узлам по пути всплытия https://learn.javascript.ru/event-delegation

2022-12-05 10:55 UTC, radkoff26 commented
Сделал)

2022-12-05 11:11 UTC, fromanywhere commented
Нет, всё еще висит на каждом li 
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/1042969/205623422-2395e34d-959a-451c-9701-9f8cf62cd74a.png">

2022-12-05 11:12 UTC, fromanywhere commented on src/js/components/Todo.js
> +            case 'checkbox':
Не припомню тега <checkbox />

2022-12-05 11:14 UTC, radkoff26 commented on src/js/components/Todo.js
> +            case 'checkbox':
упс

2022-12-05 11:14 UTC, radkoff26 commented on src/js/components/Todo.js
> +            case 'checkbox':
поправлю

2022-12-05 11:18 UTC, radkoff26 commented
сейчас сделаю listener на один только лист

2022-12-05 11:29 UTC, radkoff26 commented
Вроде готово. Извиняюсь, затупил изначально немного.

2022-12-05 11:36 UTC, fromanywhere approved these changes

2022-12-05 11:37 UTC, merged